title: Multilevel Modeling with Python
description: A step-by-step demonstration on how to conduct a multilevel regression using Python 
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker